### ISSUE TITLE
Auth.GG

### ISSUE THREAD

**Issue by UnrealBloxy** [Its-Vichy/DTG-Src#4]
How do we config Auth.GG or do we have to buy a key from you ?

**Comment by Its-Vichy** [comment]
a

**Comment by UnrealBloxy** [comment]
I guess , I'll have to figure it out
![2022-08-01 23_33_40-Sélection C__Windows_system32_cmd exe](https://user-images.githubusercontent.com/108338088/182250462-7ef4bcd9-dcf4-4a23-beaa-c06babf6e05f.png)

**Comment by Its-Vichy** [comment]
a

**Comment by UnrealBloxy** [comment]
b

**Comment by UnrealBloxy** [comment]
Managed to make it work

**Comment by Its-Vichy** [comment]
a

**Comment by Its-Vichy** [comment]
c

**Comment by UnrealBloxy** [comment]
d

**Comment by Its-Vichy** [comment]
e

**Comment by UnrealBloxy** [comment]
f
